include: all_lint_rules.yaml

analyzer:
  errors:
    included_file_warning: ignore
    todo: ignore
    missing_required_param: warning
    missing_return: warning

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    always_specify_types: false
    always_use_package_imports: false
    avoid_annotating_with_dynamic: false
    avoid_catches_without_on_clauses: false
    avoid_classes_with_only_static_members: false
    avoid_final_parameters: false
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: false
    avoid_redundant_argument_values: false
    cascade_invocations: false
    close_sinks: false
    diagnostic_describe_all_properties: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    prefer_constructors_over_static_methods: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false
    prefer_int_literals: false
    public_member_api_docs: false
    require_trailing_commas: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    sort_pub_dependencies: false
    unnecessary_final: false